agent:
  name: Cortex-R
  id: cortex_r_002
  description: >
    A reasoning-driven AI agent capable of using external tools
    and memory to solve complex tasks step-by-step.

strategy:
  planning_mode: conservative   # [conservative, exploratory]
  exploration_mode: parallel    # [parallel, sequential] (only relevant if planning_mode = exploratory)
  memory_fallback_enabled: true # after tool exploration failure
  max_steps: 3                  # max sequential agent steps
  max_lifelines_per_step: 3      # retries for each step (after primary failure)

memory:
  memory_service: true
  summarize_tool_results: true  # Always store summarized results
  tag_interactions: true        # Get tags from LLM for each interaction
  storage:
    base_dir: "memory"
    structure: "date"  # Indicates we're using date-based directory structure

llm:
  text_generation: gemini #gemini or phi4 or gemma3:12b or qwen2.5:32b-instruct-q4_0 
  embedding: nomic

persona:
  tone: concise
  verbosity: low
  behavior_tags: [rational, focused, tool-using]

mcp_servers:
  - id: math
    script: mcp_server_1.py
    cwd: "/Users/pravingadekar/Documents/EAG2/S9-Assignment"
    description: "Math, string, and code execution tools."
    capabilities: ["add", "subtract", "multiply", "divide", "power", "cbrt", "factorial", "remainder", "sin", "cos", "tan", "mine", "create_thumbnail", "strings_to_chars_to_int", "int_list_to_exponential_sum", "fibonacci_numbers"]
    basic_tools: [run_python_sandbox]
  - id: documents
    script: mcp_server_2.py
    cwd: "/Users/pravingadekar/Documents/EAG2/S9-Assignment"
    description: "Load, search and extract from static files (PDFs, webpages, etc)."
    capabilities: ["search_stored_documents", "convert_webpage_url_into_markdown", "extract_pdf"]
    basic_tools: [convert_webpage_url_into_markdown, duckduckgo_search_results]
  - id: websearch
    script: mcp_server_3.py
    cwd: "/Users/pravingadekar/Documents/EAG2/S9-Assignment"
    description: "Live web search and webpage content fetching."
    capabilities: ["duckduckgo_search_results", "download_raw_html_from_url"]
    basic_tools: [duckduckgo_search_results]
  - id: memory
    script: modules/mcp_server_memory.py
    cwd: "/Users/pravingadekar/Documents/EAG2/S9-Assignment"
    description: "Semantic search over all past agent-user conversations."
    capabilities: ["search_historical_conversations"]
    basic_tools: [search_historical_conversations]
  #   basic_tools: [get_current_conversations, search_historical_conversations]

